import type { Metadata } from "next";
import { Roboto_Condensed, PT_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto-condensed",
});

const ptSerif = PT_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-pt-serif",
});

export const metadata: Metadata = {
  title: "City News",
  description: "Generated by City News",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.variable} ${ptSerif.variable} bg-[#F0F1F2] antialiased font-sans`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
