import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto-condensed"
});

export const metadata: Metadata = {
  title: "City News",
  description: "Generated by City News"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.variable} bg-[#F0F1F2] antialiased`}
        style={{
          fontFamily:
            "var(--font-roboto-condensed), 'Times New Roman', Times, serif"
        }}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
